### ISSUE TITLE
Wikimedia Commons upload fails

### ISSUE THREAD

**Issue by ddennedy** [ddennedy/wikimedia-video-editing-server#12]
/var/www/application/logs/ reports "MediaWiki upload API error: Uploads by URL are not allowed from this domain."

**Comment by ddennedy** [comment]
I need to rewrite this part to not only use chunked HTTP POST but also run as a job.

**Comment by 80686** [comment]
I will file a bug to get our domain into the whitelist. Alternatively I can create a host record for this server in one of my already whitelisted domxains.

**Comment by ddennedy** [comment]
Let's try one of your domains. It will not be the primary address for the server since the oauth consumer is already approved. However, I can use another address for the upload URL. You can should use CNAME researcher1907.fnf.archive.org or wikimedia.meltvideo.com.

**Comment by ddennedy** [comment]
Publishing has now been converted into a background job, but it is still using the download URL method. I have a configurable download URL prefix in config.php.

**Comment by 80686** [comment]
-:[~]$> dig upload-ia1907.wikimedia.ch

;; QUESTION SECTION:
;upload-ia1907.wikimedia.ch.    IN      A

;; ANSWER SECTION:
upload-ia1907.wikimedia.ch. 86400 IN    CNAME   researcher1907.fnf.archive.org.
researcher1907.fnf.archive.org. 1798 IN A       208.70.31.97

**Comment by ddennedy** [comment]
Thanks, getting close, but POST to upload API is failing with "MediaWiki upload API error: Invalid token." It is not clear to me why at the moment.

**Comment by ddennedy** [comment]
Got past that and now I get a permission denied error:
HTTP response: {"servedby":"mw1114","error":{"code":"permissiondenied","info":"Permission denied","*":"See https:\/\/commons.wikimedia.org\/w\/api.php for API usage"}}

I get the aame thing when I use phpapilib.php with upload_file_by_url.php after I remove asyncdownload=1 and add continue= to prevent exit on warnings. (I added $post['continue'] = ''; in sendcmd().)

The URL I am using is:
http://upload-ia1907.wikimedia.ch/transcodes/k/d/kdenlive-project-test-1%20%284%29.webm

**Comment by ddennedy** [comment]
OK, upload_file.php works. So, I guess I will try chunked upload in my code next.

**Comment by ddennedy** [comment]
Fixed using file push/post with chunking.
