### ISSUE TITLE
Changes in chronological order

### ISSUE THREAD

**Issue by 80686** [ddennedy/wikimedia-video-editing-server#21]
Changes are not exactly in chronological order, should be sorted by last revision timestamp descending

**Comment by ddennedy** [comment]
They are in reverse chronological order as far as I can tell. Explain further with evidence.

**Comment by 80686** [comment]
![schnittserver](https://cloud.githubusercontent.com/assets/8996409/6136248/68531550-b16f-11e4-903c-0054e68b4362.png)

**Comment by 80686** [comment]
thanks!
