### ISSUE TITLE
WAV File on server not recognised / reported as missing

### ISSUE THREAD

**Issue by 80686** [ddennedy/wikimedia-video-editing-server#25]
I just uploaded some video files plus a wav file for an off-text.
The wav file got properly converted into an ogg file.

After uploading the kdenlive file it reports the wav file as missing.

http://wikimedia.meltvideo.com/index.php/file/18

**Comment by 80686** [comment]
Note: I uploaded the raw files and a kdenlive file using these raw files directly, rather than using proxy files. (Based on the comment by Dan that files are recognised by hash).

**Comment by ddennedy** [comment]
OK, this is fixed. Sometimes a XML file has relative file paths in the MLT XML part and absolute file paths in the Kdenlive part where the hashes are recorded, and the code was not prepared to handle that difference. Now, your project is missing the Logo.png. When you upload it, the server should automatically re-attempt to validate the project XML and render it if valid.

**Comment by 80686** [comment]
Thanks. I uploaded the logo and the file reported to be validated. What I wonder is why it only asked for one logo (see also the "files used by that project") as there are three logos in the project. The regular one is used as a background for the title (not shown here), a small inverted one with a long background is used for scrolling credits (not shown here), the big inverted one (shown) is used as outro.

Alas the rendered file misses these logos. I guess the reason is because I imported kdenlivetitles which I share among projects, so I don't have to re-do the titles for every project.

Another issue is that the actual video footage is shown as "INVALID". Some problem with the uploaded files have a different name than the ones used in the project XML? The videos are found and listed correctly in "files used by that project", though, and the proxy files are good.
Another idea I have is that the effect I am using (Color Correction -> Brightness (keyframable)) is not available on the server.

**Comment by 80686** [comment]
I made a test and downloaded all the files again from the server and put them into a new project directory.

1) The project opens with no issues or messages.

2) The videos and the WAV are fine (one just has to click "Reload Clip" on each clip to make it appear correctly in the timeline and play).

3) All logos work out of the box - but maybe the kdenlivetitles are still loaded from its original location on the harddrive.

![kdenlive](https://cloud.githubusercontent.com/assets/8996409/6200170/c451df8a-b46c-11e4-975a-5417a5af68c4.png)
![kdenlive](https://cloud.githubusercontent.com/assets/8996409/6200176/ecd2fa20-b46c-11e4-8cd9-756308db8825.png)

**Comment by ddennedy** [comment]
> What I wonder is why it only asked for one logo (see also the "files used by that project") as there are three logos in the project.

Currently, the implementation of the dependency checker only parses the top level MLT XML. Kdenlive title is XML that is embedded with the MLT XML and must be extracted, parsed, and analyzed to search for linked image files. So, that is a TODO item that was given lower priority at this early stage. There are other situations where dependent files can link to additional files such as using MLT XML (or Kdenlive XML) as virtual clip or SVG. Those will not be supported in the near term, but I will work on supporting images in kdenlivetitle XML soon.

**Comment by ddennedy** [comment]
> Another issue is that the actual video footage is shown as "INVALID".

This was a bug due to another case where the unexpected relative paths were not handled correctly. This has been fixed and a re-render of the project requested, which turned out fine (sans images in the title clips.) Please see the render result now.

**Comment by 80686** [comment]
rendering is fine now! I saw some issues with the effects and the scrolling credits but I assume that the kdenlive file I uploaded is not the latest version, that the issues are in that file. I will check.

That kdenlivetitles don't work yet is an acceptable limitation give the short timeframe to get the product up running. It is just unfortunate that all my existing video projects look that way ;-)

**Comment by ddennedy** [comment]
>  I saw some issues with the effects

I need to install the de_DE.UTF-8 locale on the server since the XML was saved under that locale and numeric values have comma as the decimal separator. I re-rendered and that should look better now. Please verify.

**Comment by 80686** [comment]
Right, the color is correct now. The credits are still strangely cut but I assume that is because of the missing kdenlivetitle which should be underneath the scrolling text.

**Comment by ddennedy** [comment]
> I saw some issues with the ... scrolling credits

The problem here is that I am using a recent build of Shotcut for the ffmpeg and melt implementation on the server since I trust its build to be better and more complete than Debian/Ubuntu's. However, in this build, the MLT kdenlivetitle producer is linked against Qt 5 instead of Qt 4 since Shotcut is a Qt 5 app, and I think that is the problem. It seems basic titles work fine in Qt 5, but perhaps not the animated effects or all features. I will install melt and ffmpeg from PPA/Ubuntu on the server running 14.04 and re-test some things like transcodes and renders to see how things go... I am having trouble installing software from packages on the server today due to the way this VM is setup and point to archive.org apt repos.

**Comment by 80686** [comment]
Before dong all that I would rather download the kdenlive file and test it on your machine and check if the credits work or not.

**Comment by ddennedy** [comment]
The credits look fine on my machine in Kdenlive but not when loaded as a virtual clip in Shotcut, which is why I think it is a Qt 4 vs. 5 problem. The archive.org apt repos are strangely giving HTTP 403 forbidden errors, and the Kdenlive nightly builds do not bundle Qt 4 libs (Shotcut bundles Qt 5 libs) to make that an option at the moment. I have to ask Jake for help.

**Comment by 80686** [comment]
Ok, thanks!

**Comment by ddennedy** [comment]
OK, we got the apt problem resolved on the server, but something in their policy prevents installing mlt or even the mlt ppa:sunab/kdenlive-release! So, I installed a nightly partially self-contained build of kdenlive and Qt 4 libs from apt repo, and that works. I issued a re-render, and now the credits animation looks correct. See commit 26271dfd04d53faaebd97b76407b13f48f465fe6.

Now, that leaves extracting and parsing an embedded kdenlivetitle XML to locate content elements with a url attribute to locate additional dependencies.

**Comment by ddennedy** [comment]
Manuel, please upload the following 2 files to help continue work on the kdenlivetitle xml parsing:
/home/manuel/kdenlive/titles/c359bd0f31e1e7a9dced65953dfb623c.titlepart
/home/manuel/kdenlive/titles/210c5130fcb3a4b40758ff214344b9a9.titlepart

**Comment by 80686** [comment]
uploaded now as 
http://wikimedia.meltvideo.com/index.php/file/49
http://wikimedia.meltvideo.com/index.php/file/48

**Comment by ddennedy** [comment]
Yay! Now, the titleparts in a Kdenlive title are handled correctly from upload, through validation, for download, and to render. If you look at the rendered output for file/18 now, you will see the rendered titleparts!
