### ISSUE TITLE
Renderer: "A preview function allows to inspect the finished WebM file before it is transferred."

### ISSUE THREAD

**Issue by ddennedy** [ddennedy/wikimedia-video-editing-server#9]
The project is rendered to high bitrate at project resolution. This means currently preview requires a high bandwidth connection or a download-and-review. The requirements/spec. does not call for rendering multiple resolutions and bitrates for proxy files and project renderings to facilitate device- and bandwidth-friendly online previewing of videos.

**Comment by 80686** [comment]
what we could add - in general for all files on the Schnittserver - is a preview in browser (no re-encoding for now, just original quality)

* Is there a good WebM open source player for browsers?
* Should we use "Timed Media Handler" from Wikimedia Commons / MediaWiki?

**Comment by ddennedy** [comment]
Well, the "Transcoded" and "Rendered" status links to ogg/webm files that ought to play in the browser. The other "download" links send HTTP headers to prevent the browser from viewing the file. Of course, it may also be nice to have a nicer on-page lightbox-style player; however, I personally feel that does not really provide a better user experience.

I think one thing will come up soon is better integration with the archive.org file repository. In that case, after the upload is archived, archive.org will transcode it to different levels, and we can link to the corresponding page.

Now, if the page were to have an embedded player, that is another story for the user experience. However, will have to see how that can be integrated with an archive.org/wikimedia transcode.
